Features/production
farajzada/turing-course-jbe pull request #15
Opened 2024-12-15 10:45 UTC by farajzada

2024-12-18 17:27 UTC, sabuhihuseynov commented on src/turing_quizzes/turingLabs/turingLabs01/Application.java
> +        Movie[] movies = new Movie[0];
instead send movies to each method you can declare it on class level

2024-12-18 17:32 UTC, sabuhihuseynov commented on src/turing_quizzes/turingLabs/turingLabs01/Application.java
> +            System.out.println(movies[i].getName() + ":" + movies[i].getRating());
you can override toString() method, and then just use movies object inside sout

2024-12-18 17:35 UTC, sabuhihuseynov commented on src/turing_quizzes/turingLabs/turingLabs01/Application.java
> +            if (movies[i].getName().equals(name)) {
it will be good make our searching case insensetive, with `equalsIgnoreCase()`

2024-12-18 17:35 UTC, sabuhihuseynov commented on src/turing_quizzes/turingLabs/turingLabs01/Application.java
> +        if (index >= 0) {
check should be index != -1 for readablity

2024-12-18 17:35 UTC, sabuhihuseynov commented on src/turing_quizzes/turingLabs/turingLabs01/Application.java
> +        if (index >= 0) {
check should be index != -1 for readablity

2024-12-18 17:37 UTC, sabuhihuseynov commented on src/turing_quizzes/turingLabs/turingLabs01/Application.java
> +            {
what this block that for?

2024-12-18 17:39 UTC, sabuhihuseynov requested changes
pls look

2024-12-19 00:27 UTC, farajzada commented on src/turing_quizzes/turingLabs/turingLabs01/Application.java
> +            {
I wrote else option the first time, then İDE said it was unnecessary, I deleted the else block and İDE didn't show a problem, so I forgot and it stayed there.😂

2024-12-19 01:26 UTC, farajzada commented
> pls look

all comments updated

2024-12-25 13:25 UTC, merged